# Generated by Django 6.1 on 2026-08-28 15:22

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=None, null=True)),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('reported', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='api.category')),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
