# Generated by Django 6.1 on 2026-08-28 15:22

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('word'), name='word_word_ci_unique'),
        ),
    ]
