# Generated by Django 6.1 on 2026-08-25 09:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('word'), name='word_word_ci_unique'),
        ),
    ]
