# Generated by Django 6.1 on 2026-08-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_category_name_ci_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='reported_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
