# Generated by Django 6.1 on 2026-08-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_options_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
