# Generated by Django 6.1 on 2026-08-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='addressed',
            field=models.BooleanField(default=False),
        ),
    ]
