# Generated by Django 6.1 on 2026-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feedback_addressed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['card_order', 'name']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='card_order',
        ),
        migrations.AddField(
            model_name='category',
            name='board_order',
            field=models.IntegerField(default=0),
        ),
    ]
